channels:
- conda-forge
dependencies:
- python=3.12.5
- pip<=25.3
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - numpy==2.2.3
  - pandas==2.2.3
  - psutil==7.0.0
  - pyarrow==19.0.1
  - scikit-learn==1.7.2
  - scipy==1.15.2
  - typing==3.7.4.3
name: mlflow-env
